Fix Bisq 2 onion-grater profile
Whonix/onion-grater pull request #11
Opened 2024-06-11 01:58 UTC by alvasw

- Remove deprecated SETEVENTS command
- Add missing ADD_ONION pattern and replacement
- Fix HS_DESC UPLOAD pattern and replacement
- Add missing HS_DESC FAILED pattern and replacement

Ref: bisq-network/bisq2#1894

2024-06-11 02:13 UTC, alvasw commented
Hi @adrelanos,

I'm one of the Bisq core contributors and worked on the Bisq 2 Whonix support over the last few weeks. Bisq used the jtorctl library from the Tor Project [1] until now. Unforunately, is is not maintained by the Tor Project anymore and outdated. We re-implemented the Tor Control Protocol in Java to add Whonix/onion-grater support.

This commit and the commits in Bisq are signed with the same GPG key (see [2] and [3]).

[1] https://github.com/torproject/jtorctl
[2] https://github.com/bisq-network/bisq/pulls?q=is%3Apr+author%3Aalvasw+
[3] https://github.com/bisq-network/bisq2/pulls?q=is%3Apr+author%3Aalvasw+

2024-06-13 06:58 UTC, nyxnor requested changes

2024-06-13 06:58 UTC, nyxnor commented on usr/share/doc/onion-grater-merger/examples/40_bisq.yml
> +          replacement: '650 HS_DESC UPLOAD {} {} {} {} {}'
Are all those fields in `HS_DESC UPLOAD` required to be seen by the Bisq client?

[Cwtch can use less information](https://github.com/Whonix/onion-grater/blob/master/usr/share/doc/onion-grater-merger/examples/40_cwtch.yml#L71-L72) and [Onionshare also](https://github.com/Whonix/onion-grater/blob/master/usr/share/doc/onion-grater-merger/examples/40_onionshare.yml#L89-L90).

2024-06-13 06:59 UTC, nyxnor commented
Thanks for contributing!

2024-06-13 07:01 UTC, nyxnor commented
For this PR to get merged, we need to test Bisq2 release greater than 2.0.4. https://github.com/bisq-network/bisq2/issues/1894#issuecomment-2164679353

2024-09-19 15:30 UTC, alvasw commented
Please apologize my late reply!

> Are all those fields in HS_DESC UPLOAD required to be seen by the Bisq client?

Yes, it's used as a DoS defense in the handshake. When a Bisq client receives an incoming connection from another peer, the connecting peer proves its onion address ownership and the other peer verifies that the onion address is online by checking whether the onion service's hidden service descriptors were uploaded.

So if Alice connects to Bob before Alice has uploaded her hidden service descriptors, Bob will reject the connection.

We could count the number of hidden service descriptor uploads and successes/failures instead of verifying the directories.

2024-09-19 15:31 UTC, alvasw commented on usr/share/doc/onion-grater-merger/examples/40_bisq.yml
> +          replacement: '650 HS_DESC UPLOAD {} {} {} {} {}'
Yes, it's used as a DoS defense in the handshake. When a Bisq client receives an incoming connection from another peer, the connecting peer proves its onion address ownership and the other peer verifies that the onion address is online by checking whether the onion service's hidden service descriptors were uploaded.

So if Alice connects to Bob before Alice has uploaded her hidden service descriptors, Bob will reject the connection.

2024-09-26 15:48 UTC, nyxnor commented
Tested on Bisq2.1.0. It is working!

2024-09-27 01:24 UTC, adrelanos commented
Thank you!

2024-09-27 01:24 UTC, merged